### ISSUE TITLE
Fedora Rawhide now has GNOME Shell 3.17.1

### ISSUE THREAD

**Issue by russel** [UshakovVasilii/gnome-shell-extension-freon#10]
It appears that Fedora Rawhide has updated to GNOME Shell 3.17.1 and so Freon fails to start out of the box. I tried adding "3.17" to the list of versions in metadata.json, but that didn't seem to work – unless I just did something wrong…

**Comment by UshakovVasilii** [comment]
I installed Fedora.
Don't work with `3.17`...  Don't work with `3.18`...
Work with `3.17.1`!

You are using not latest gnome version. You need just skip version checking:
`gsettings set org.gnome.shell disable-extension-version-validation "true"`

**Comment by russel** [comment]
Actually I do have 3.17.1, still doesn't work for me with version checking even though I put 3.17 in the prefs.js file. Or should I have done something other?

**Comment by russel** [comment]
Of course switching off version checking, fixes the other extensions as well :-)
