### ISSUE TITLE
List with NaN when NVIDIA is disabled

### ISSUE THREAD

**Issue by yustnip** [UshakovVasilii/gnome-shell-extension-freon#107]
After enabled Intel PRIME Profile via nvidia-prime I got the NVIDIA-list with NaN values.

![screenshot from 2018-10-18 22-24-50](https://user-images.githubusercontent.com/9950871/47179266-513d7400-d326-11e8-809c-05181dd415ac.png)

When NVIDIA PRIME Profile is enabled all's fine.

![screenshot from 2018-10-18 22-30-40](https://user-images.githubusercontent.com/9950871/47179283-5e5a6300-d326-11e8-9e1b-ba0605cc57ca.png)

Video Card Temperature Utility is NVIDIA. Ubuntu 18.04.

**Comment by UshakovVasilii** [comment]
Please provide `nvidia-settings -q gpucoretemp -t` and `nvidia-settings -q gpus` output for first case.

**Comment by yustnip** [comment]
nvidia-settings -q gpucoretemp -t

```

ERROR: NVIDIA driver is not loaded

ERROR: Error querying enabled displays on GPU 0 (Missing Extension).

ERROR: Error querying connected displays on GPU 0 (Missing Extension).

ERROR: Error resolving target specification '' (No targets match target
       specification), specified in query 'gpucoretemp'.

```

nvidia-settings -q gpus

```

ERROR: NVIDIA driver is not loaded

ERROR: Error querying enabled displays on GPU 0 (Missing Extension).

ERROR: Error querying connected displays on GPU 0 (Missing Extension).


```

**Comment by yustnip** [comment]
Possible solution - https://github.com/UshakovVasilii/gnome-shell-extension-freon/pull/108

**Comment by UshakovVasilii** [comment]
Merged
