### ISSUE TITLE
Negative voltages has a double minus signs.

### ISSUE THREAD

**Issue by squall77it** [UshakovVasilii/gnome-shell-extension-freon#110]
Negative voltages has a double minus signs, Ex: -12.55V is --12.55V.

I fix it modifing the line 377 of extensions.js from:
`value:_("%s%.2fV").format(((voltage.volt >= 0) ? '+' : '-'),`
to
`value:_("%s%.2fV").format(((voltage.volt >= 0) ? '+' : ''),`
because numbers less then 0 already have the minus sign.

Before:
![freon_issue](https://user-images.githubusercontent.com/5853097/47755163-973af600-dc9d-11e8-8df6-e4ad5055f683.png)
After:
![freon_fixed](https://user-images.githubusercontent.com/5853097/47755168-a02bc780-dc9d-11e8-8b9b-11f77b2c1316.png)

**Comment by AlexWayfer** [comment]
Negative voltage — is it OK?

**Comment by AlexWayfer** [comment]
> Yes is OK
> https://en.wikipedia.org/wiki/ATX#Power_supply

Thank you!
