### ISSUE TITLE
Make the UI more self-explanatory, or link to the wiki

### ISSUE THREAD

**Issue by audreytoskin** [UshakovVasilii/gnome-shell-extension-freon#113]
I created pull request #112, partly to make the link from the repository README to the wiki more prominent. But it's still possible for users to miss the documentation and get confused -- for example, if they only read the description on the GNOME Shell Extensions website, or if they discover Freon through their distro's packages and don't know about looking in `/usr/share/doc/` for documentation -- and it's extra important for users to *actually read the docs* when it comes to using Freon.

I'm only a beginner developer myself, but I think one way to improve this would to try directing users to the wiki *from the Freon UI*.

* Currently there's a notification if you open Freon without having run `sensors-detect`. Maybe this could be changed to a notification that *always* appears on first run, whether or not the user has previously used lm_sensors, and this notification would include a link to the wiki.
* Or, perhaps the top-bar drop-down menu and/or the Freon settings window could permanently display text somewhere which links to the wiki.
* Or, both.

What do you think?

**Comment by UshakovVasilii** [comment]
I will add link to WiKi like `Sensors Settings` button

**Comment by UshakovVasilii** [comment]
done
![screenshot from 2018-11-18 10-15-21](https://user-images.githubusercontent.com/3512063/48669697-f06aac80-eb1a-11e8-9e55-ba45d8de1ea4.png)

**Comment by terrycloth** [comment]
Great, thanks!
