### ISSUE TITLE
GPU temp not showing in taskbar but extension gets the data

### ISSUE THREAD

**Issue by Kallestofeles** [UshakovVasilii/gnome-shell-extension-freon#125]
Greetings,

The issue I have is that the Nvidia GPU data is received by the extension, but is not shown in the titlebar despite being enabled in the options. It seems that the extent of the titlebar item is squeezed together and that is why it only shows the CPU temp and three dots. Has anyone encountered this and know a solution?

OS: Arch + GNOME Shell 3.30.2
CPU: Ryzen 2700X
GPU: 2080Ti

![image](https://user-images.githubusercontent.com/3207177/54342183-7bc8fa00-4644-11e9-9d6e-17bbeeb853db.png)

**Comment by UshakovVasilii** [comment]
Looks like `GeForce RTX 2080 Ti` element is not checked
![Screenshot from 2019-03-14 14-38-04](https://user-images.githubusercontent.com/3512063/54354152-f9056680-4666-11e9-9fdb-50c3d86fdf32.jpg)

**Comment by Kallestofeles** [comment]
My god I feel stupid. Thank you for pointing out the obvious! Got it perfectly showing up now. :)
