### ISSUE TITLE
TypeError: ExtensionUtils.initTranslations is not a function

### ISSUE THREAD

**Issue by terrycloth** [UshakovVasilii/gnome-shell-extension-freon#131]
I maintain the RPM package of Freon for Fedora. After updating to Freon version 36 on Fedora 29 Workstation with GNOME Shell 3.30.2, Freon no longer loads. GNOME Tweaks shows the error icon next to Freon, and when you click on the gear button, you get the error message below.

Possibly related to #126?
```
TypeError: ExtensionUtils.initTranslations is not a function

Stack trace:
  init@/usr/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/prefs.js:17:5
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:68:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:82:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43
```

**Comment by jlmagee** [comment]
I'm having this issue on F29 as well. Downgrading Freon to 34 does not solve the problem. It worked before these updates were installed this morning
Installing:
 kernel                                      x86_64 5.0.5-200.fc29                     updates                        30 k
 kernel-core                                 x86_64 5.0.5-200.fc29                     updates                        26 M
 kernel-devel                                x86_64 5.0.5-200.fc29                     updates                        13 M
 kernel-modules                              x86_64 5.0.5-200.fc29                     updates                        28 M
 kernel-modules-extra                        x86_64 5.0.5-200.fc29                     updates                       2.1 M
Upgrading:
 cockpit                                     x86_64 191-1.fc29                         group_cockpit-cockpit-preview  32 k
 cockpit-bridge                              x86_64 191-1.fc29                         group_cockpit-cockpit-preview 548 k
 cockpit-dashboard                           noarch 191-1.fc29                         group_cockpit-cockpit-preview 145 k
 cockpit-debuginfo                           x86_64 191-1.fc29                         group_cockpit-cockpit-preview  15 M
 cockpit-debugsource                         x86_64 191-1.fc29                         group_cockpit-cockpit-preview 297 k
 cockpit-doc                                 noarch 191-1.fc29                         group_cockpit-cockpit-preview 635 k
 cockpit-docker                              x86_64 191-1.fc29                         group_cockpit-cockpit-preview 372 k
 cockpit-kdump                               noarch 191-1.fc29                         group_cockpit-cockpit-preview 123 k
 cockpit-kubernetes                          x86_64 191-1.fc29                         group_cockpit-cockpit-preview 4.4 M
 cockpit-machines                            noarch 191-1.fc29                         group_cockpit-cockpit-preview 456 k
 cockpit-machines-ovirt                      noarch 191-1.fc29                         group_cockpit-cockpit-preview 454 k
 cockpit-networkmanager                      noarch 191-1.fc29                         group_cockpit-cockpit-preview 235 k
 cockpit-packagekit                          noarch 191-1.fc29                         group_cockpit-cockpit-preview 326 k
 cockpit-pcp                                 x86_64 191-1.fc29                         group_cockpit-cockpit-preview  74 k
 cockpit-selinux                             noarch 191-1.fc29                         group_cockpit-cockpit-preview 167 k
 cockpit-sosreport                           noarch 191-1.fc29                         group_cockpit-cockpit-preview  52 k
 cockpit-storaged                            noarch 191-1.fc29                         group_cockpit-cockpit-preview 394 k
 cockpit-system                              noarch 191-1.fc29                         group_cockpit-cockpit-preview 1.1 M
 cockpit-tests                               x86_64 191-1.fc29                         group_cockpit-cockpit-preview 262 k
 cockpit-ws                                  x86_64 191-1.fc29                         group_cockpit-cockpit-preview 788 k
 appstream-data                              noarch 29-10.fc29                         updates                        17 M
 audit                                       x86_64 3.0-0.7.20190326git03e7489.fc29    updates                       227 k
 audit-libs                                  x86_64 3.0-0.7.20190326git03e7489.fc29    updates                       106 k
 container-selinux                           noarch 2:2.94-1.git1e99f1d.fc29           updates                        46 k
 environment-modules                         x86_64 4.2.3-1.fc29                       updates                       309 k
 firefox                                     x86_64 66.0.2-1.fc29                      updates                        89 M
 flatpak                                     x86_64 1.2.4-1.fc29                       updates                       1.0 M
 flatpak-libs                                x86_64 1.2.4-1.fc29                       updates                       344 k
 fuse-overlayfs                              x86_64 0.3-8.dev.gita6958ce.fc29          updates                        49 k
 git-cola                                    noarch 3.3-1.fc29                         updates                       982 k
 gnome-shell-extension-no-topleft-hot-corner noarch 19.0-1.fc29                        updates                        17 k
 hwdata                                      noarch 0.322-1.fc29                       updates                       1.5 M
 java-1.8.0-openjdk                          x86_64 1:1.8.0.201.b09-6.fc29             updates                       239 k
 java-1.8.0-openjdk-devel                    x86_64 1:1.8.0.201.b09-6.fc29             updates                       9.8 M
 java-1.8.0-openjdk-headless                 x86_64 1:1.8.0.201.b09-6.fc29             updates                        32 M
 java-11-openjdk                             x86_64 1:11.0.2.7-7.fc29                  updates                       219 k
 java-11-openjdk-demo                        x86_64 1:11.0.2.7-7.fc29                  updates                       4.3 M
 java-11-openjdk-demo-slowdebug              x86_64 1:11.0.2.7-7.fc29                  updates                       4.3 M
 java-11-openjdk-devel                       x86_64 1:11.0.2.7-7.fc29                  updates                       3.3 M
 java-11-openjdk-devel-slowdebug             x86_64 1:11.0.2.7-7.fc29                  updates                       3.3 M
 java-11-openjdk-headless                    x86_64 1:11.0.2.7-7.fc29                  updates                        39 M
 java-11-openjdk-headless-slowdebug          x86_64 1:11.0.2.7-7.fc29                  updates                        41 M
 java-11-openjdk-javadoc                     x86_64 1:11.0.2.7-7.fc29                  updates                        16 M
 java-11-openjdk-javadoc-slowdebug           x86_64 1:11.0.2.7-7.fc29                  updates                        16 M
 java-11-openjdk-javadoc-zip                 x86_64 1:11.0.2.7-7.fc29                  updates                        42 M
 java-11-openjdk-javadoc-zip-slowdebug       x86_64 1:11.0.2.7-7.fc29                  updates                        42 M
 java-11-openjdk-jmods                       x86_64 1:11.0.2.7-7.fc29                  updates                       321 M
 java-11-openjdk-jmods-slowdebug             x86_64 1:11.0.2.7-7.fc29                  updates                       200 M
 java-11-openjdk-slowdebug                   x86_64 1:11.0.2.7-7.fc29                  updates                       219 k
 java-11-openjdk-src                         x86_64 1:11.0.2.7-7.fc29                  updates                        50 M
 java-11-openjdk-src-slowdebug               x86_64 1:11.0.2.7-7.fc29                  updates                        50 M
 kernel-cross-headers                        x86_64 5.0.5-200.fc29                     updates                       5.9 M
 kernel-headers                              x86_64 5.0.5-200.fc29                     updates                       1.2 M
 kernel-tools                                x86_64 5.0.5-200.fc29                     updates                       164 k
 kernel-tools-libs                           x86_64 5.0.5-200.fc29                     updates                        19 k
 librepo                                     x86_64 1.9.6-2.fc29                       updates                        87 k
 libsolv                                     x86_64 0.7.4-2.fc29                       updates                       372 k
 libxmlb                                     x86_64 0.1.8-1.fc29                       updates                        82 k
 ntfs-3g                                     x86_64 2:2017.3.23-11.fc29                updates                       257 k
 ntfsprogs                                   x86_64 2:2017.3.23-11.fc29                updates                       357 k
 perl-DateTime-TimeZone                      noarch 2.34-1.fc29                        updates                       417 k
 perl-Module-CoreList                        noarch 1:5.20190320-1.fc29                updates                        84 k
 python2-audit                               x86_64 3.0-0.7.20190326git03e7489.fc29    updates                        73 k
 python2-librepo                             x86_64 1.9.6-2.fc29                       updates                        46 k
 python3-audit                               x86_64 3.0-0.7.20190326git03e7489.fc29    updates                        73 k
 python3-librepo                             x86_64 1.9.6-2.fc29                       updates                        46 k
 rpm-ostree                                  x86_64 2019.3-1.fc29                      updates                       832 k
 rpm-ostree-libs                             x86_64 2019.3-1.fc29                      updates                       1.4 M
 sos                                         noarch 3.7-1.fc29                         updates                       476 k
 tzdata                                      noarch 2019a-1.fc29                       updates                       428 k
 tzdata-java                                 noarch 2019a-1.fc29                       updates                       152 k
 uboot-images-armv7                          noarch 2018.09-3.fc29                     updates                       8.5 M
 uboot-images-armv8                          noarch 2018.09-3.fc29                     updates                       2.8 M
 uboot-tools                                 x86_64 2018.09-3.fc29                     updates                       356 k
 vim-common                                  x86_64 2:8.1.1099-1.fc29                  updates                       6.6 M
 vim-enhanced                                x86_64 2:8.1.1099-1.fc29                  updates                       1.3 M
 vim-filesystem                              noarch 2:8.1.1099-1.fc29                  updates                        29 k
 vim-minimal                                 x86_64 2:8.1.1099-1.fc29                  updates                       558 k
 whois                                       x86_64 5.4.2-1.fc29                       updates                        69 k
 whois-nls                                   noarch 5.4.2-1.fc29                       updates                        32 k
 wine-filesystem                             noarch 4.5-1.fc29                         updates                        46 k
 wine-times-new-roman-fonts                  noarch 4.5-1.fc29                         updates                       105 k
 wine-times-new-roman-fonts-system           noarch 4.5-1.fc29                         updates                        11 k
 wine-wingdings-fonts                        noarch 4.5-1.fc29                         updates                        24 k
 wine-wingdings-fonts-system                 noarch 4.5-1.fc29                         updates                        11 k
 zchunk-libs                                 x86_64 1.1.0-1.fc29                       updates                        46 k
 google-chrome-beta                          x86_64 74.0.3729.61-1                     google-chrome-beta             57 M
 google-chrome-stable                        x86_64 73.0.3683.103-1                    google-chrome-beta             55 M
 google-chrome-unstable                      x86_64 75.0.3753.4-1                      google-chrome-beta             57 M
 ffmpeg                                      x86_64 4.0.4-1.fc29                       rpmfusion-free-updates        1.3 M
 ffmpeg-libs                                 x86_64 4.0.4-1.fc29                       rpmfusion-free-updates        6.6 M
 libavdevice                                 x86_64 4.0.4-1.fc29                       rpmfusion-free-updates         68 k
Installing dependencies:
 kernel-debug-devel                          x86_64 5.0.5-200.fc29                     updates                        13 M
Removing:
 kernel                                      x86_64 4.20.14-200.fc29                   @updates                        0  
 kernel-core                                 x86_64 4.20.14-200.fc29                   @updates                       61 M
 kernel-devel                                x86_64 4.20.14-200.fc29                   @updates                       51 M
 kernel-modules                              x86_64 4.20.14-200.fc29                   @updates                       28 M
 kernel-modules-extra                        x86_64 4.20.14-200.fc29                   @updates                      2.1 M

I couldn't spot the offender

**Comment by tomporter518** [comment]
@jlmagee As I recall (when I ran into this), version 34 won't work for different reasons. I manually downloaded gnome-shell-extension-freon-35-1.fc29.noarch.rpm from koji and installed (over/downgraded via rpm) to get a working version. Until 36 is fixed or pulled from the repo, you will have to ignore it's upgrade request when checking. I add '--exclude=*freon' when running dnf.

**Comment by UshakovVasilii** [comment]
`ExtensionUtils.initTranslations` exist in gnome-shell 3.32. Correct version for 3.30 should be provided by https://extensions.gnome.org/extension/841/freon/

**Comment by jlmagee** [comment]
This is totally unresponsive for downstream Fedora 29 users. For at least the last 10 releases of Fedora, extensions.gnome.org produces this error

"We cannot detect a running copy of GNOME on this system, so some parts of the interface may be disabled. See our troubleshooting entry for more information."

 I'll try the @tomporter518 suggestion.

fyi @terrycloth

**Comment by jlmagee** [comment]
@tomporter518 @terrycloth Thanks. Found a 35.1 rpm and it worked.  
@UshakovVasilii No thanks to you.

**Comment by UshakovVasilii** [comment]
@jlmagee This problem related to rpm package, extension work on 3.30 and 3.32 fine.
master support 3.32 only.

**Comment by UshakovVasilii** [comment]
![Screenshot from 2019-04-09 11-07-14](https://user-images.githubusercontent.com/3512063/55783717-bb55fb00-5ab7-11e9-83f6-fec8fd5d280d.png)

**Comment by terrycloth** [comment]
Ushakov is right, it was my mistake pushing Freon 36 to Fedora 29 in the first place. I've [pushed an update](https://bodhi.fedoraproject.org/updates/gnome-shell-extension-freon-35-3.fc29) to revert it back to Freon 35. It's in the "testing" phase right now, but I've confirmed it actually works this time, so in the meanwhile you can also [download the RPM](https://kojipkgs.fedoraproject.org//packages/gnome-shell-extension-freon/35/3.fc29/noarch/gnome-shell-extension-freon-35-3.fc29.noarch.rpm) to install right away.
