### ISSUE TITLE
Cannot display temperatures in airplane mode

### ISSUE THREAD

**Issue by BlueBeetle97** [UshakovVasilii/gnome-shell-extension-freon#132]
When WiFi is on freon displays temperatures properly, but when on airplane mode, no temperatures are displayed.
![Screenshot from 2019-04-06 17-31-03](https://user-images.githubusercontent.com/23264270/55671028-e9023080-587a-11e9-8de4-bfe84a7144d2.png)
![Screenshot from 2019-04-06 17-28-23](https://user-images.githubusercontent.com/23264270/55671030-f15a6b80-587a-11e9-877d-776e9bcbd5d7.png)

**Comment by UshakovVasilii** [comment]
Workaround https://github.com/UshakovVasilii/gnome-shell-extension-freon/wiki/FAQ#error-in-sensors-output
