### ISSUE TITLE
Broken in 19.04 gnome-shell 3.32 after recent update

### ISSUE THREAD

**Issue by isness** [UshakovVasilii/gnome-shell-extension-freon#135]
Recently updated from extensions.gnome.org and the extension fails to load although it worked fine before.

Cloning and copying the contents from freon@UshakovVasilii_Github.yahoo.com folder in this repo fixes the issue. Something went wrong with the recent commit.

**Comment by UshakovVasilii** [comment]
Yep, fixed by https://github.com/UshakovVasilii/gnome-shell-extension-freon/commit/a006cea782f25595e91dcf5853f97535983ac4db
