### ISSUE TITLE
Blacklist some of the sensors

### ISSUE THREAD

**Issue by tpimh** [UshakovVasilii/gnome-shell-extension-freon#138]
There are some sensors (not just temperature, but also rpm and voltage) shown that either show 0 or maximum value or other values that I just don't care about. They just take up space and also affect maximum and average temperature calculations. It would be nice to choose which sensors are shown (and maybe also rename them).

**Comment by UshakovVasilii** [comment]
I think it should be done on lm_sensors side https://github.com/UshakovVasilii/gnome-shell-extension-freon/wiki/FAQ#system-to-hang-every-n-second

**Comment by jonasmalacofilho** [comment]
The FAQ now has specific topics related to this:

 - [How do I rename sensors in the list?](https://github.com/UshakovVasilii/gnome-shell-extension-freon/wiki/FAQ#how-do-i-rename-sensors-in-the-list)
 - [How do I hide sensors from the list?](https://github.com/UshakovVasilii/gnome-shell-extension-freon/wiki/FAQ#how-do-i-hide-sensors-from-the-list)

---

@UshakovVasilii I think this can be closed too.
