### ISSUE TITLE
Add option to display current CPU and GPU utilization

### ISSUE THREAD

**Issue by Strykar** [UshakovVasilii/gnome-shell-extension-freon#139]
It'd be nice to view temperatures and utilization in the same plugin.

**Comment by UshakovVasilii** [comment]
It is out of this extension, https://extensions.gnome.org/extension/120/system-monitor/ good for this

**Comment by UshakovVasilii** [comment]
![Screenshot from 2019-07-06 06-45-46](https://user-images.githubusercontent.com/3512063/60751164-eb7b4000-9fb9-11e9-804c-7dfa2e33b2bc.png)
