### ISSUE TITLE
Support for Custom Labels

### ISSUE THREAD

**Issue by moriel5** [UshakovVasilii/gnome-shell-extension-freon#143]
This is a follow up to #142.
Can you please add support for Custom labels for the readings? It could really help understanding which reading is which if they could be renamed, and then, using my previous example, I could rename the GPU "temp1" to something like "Radeon HD6950", etc..

**Comment by UshakovVasilii** [comment]
I think it should be done on lm-sensors side. Not necessary to duplicate functionality.

**Comment by moriel5** [comment]
Thanks, I did not that lm-sensors worked that way.

**Comment by moriel5** [comment]
Update: I had just checked, and sensors.conf (sensors3.conf, in my case), does not contain all of the sensors (some are handled by other sources, such as the my Intel AX200 being handled by `iwlwifi`).
What to do in such a situation?

**Comment by jonasmalacofilho** [comment]
You'll generally want to add your own .conf file in `/etc/sensors.d/`.

Just as an example, here's mine (I actually have another two, the other ones deals with the low level details of my motherboard... this is the one I use specifically to customize the output of sensors and Freon):

```
$ cat /etc/sensors.d/custom.conf 
chip "nct6793-*"

  label temp8 "CPU VCC VR Temperature"
  label fan2 "AIO Pump Speed (bkp)"
  set fan2_min 1800
  ignore fan1  # vrm fan with no sense pin
  ignore fan3  # n/c
  ignore fan5  # n/c
  ignore fan6  # n/c
  ignore intrusion0
  ignore intrusion1

chip "krakenx-*"

  label temp1 "AIO Liquid Temperature"
  label fan1 "AIO Fan Speed"
  label fan2 "AIO Pump Speed"

chip "smart_device-*"

  label fan1 "Exhaust Fan Speed"
  label curr1 "Exhaust Fan Current"
  label in0 "Exhaust Fan Voltage"

  label fan2 "Test Cooler Speed"
  label curr2 "Test Cooler Current"
  label in1 "Test Cooler Voltage"

  label fan3 "Intake Fan Speed"
  label curr3 "Intake Fan Current"
  label in2 "Intake Fan Voltage"
```

**Comment by moriel5** [comment]
Thanks, I'll try that when I have the time.
