### ISSUE TITLE
Broken on 3.34

### ISSUE THREAD

**Issue by otaj** [UshakovVasilii/gnome-shell-extension-freon#146]
Hi,

Today I updated gnome-shell to 3.34 and checked, whether something stopped working - and your extension was the only one.

Error from looking glass is:
```
Error: Wrong type undefined; object GIcon expected
```

Sadly, I don't have enough experience debugging GS extensions (and JS in general), so I don't know what other steps should I take.

**Comment by UshakovVasilii** [comment]
Looks like getter:
```
    get gicon() {
        return this._gIcon;
    }
```
Is not called after `item.gicon`. I don't know what is wrong with gjs yet

**Comment by jonasmalacofilho** [comment]
Possibly related to jose1711/gnome-shell-extension-sensory-perception@66542326660f769f99a5890bb927146a88664b74.

**Comment by UshakovVasilii** [comment]
offtopic: TopIcons-plus not work, I cannot use Parcellite, I cannot switch language by Shift+Alt. I liked GNOME, but it unusable now  Xfce? )))

**Comment by kouros17** [comment]
@UshakovVasili you can use KStatusNotifierItem/AppIndicator Support

**Comment by UshakovVasilii** [comment]
Is extension work on 3.34 now?

**Comment by jonasmalacofilho** [comment]
It's working on my laptop with 3.34.

What issues are you seeing?

**Comment by UshakovVasilii** [comment]
Thanks! I will release it on extensions.gnome.org . I cannot check it, I'm using Xfce now.

**Comment by jonasmalacofilho** [comment]
Off-topic: how are you liking Xfce these days/after coming from a recent Gnome?

**Comment by UshakovVasilii** [comment]
@jonasmalacofilho  I miss windows live preview (( I very like it in gnome-shell. Xfce has Xfdashboard but it is not same.
Also I like this extension more than Xfce temperature applet))
Other things good. (I can switch keyboard layout by Shift-alt, I can open terminator from file manager, DE is lite, stable and configurable. I had problem with WICD, I installed NetworkManager instead, Xfce work good with NetworkManager)

**Comment by jonasmalacofilho** [comment]
@UshakovVasilii thanks!
