### ISSUE TITLE
Does not update temps with gnome 3.34

### ISSUE THREAD

**Issue by Trolloldem** [UshakovVasilii/gnome-shell-extension-freon#147]
The extension is running but it does not update the values shown in the top right bar. Also it is not possible to see the menu by right clicking on it. 
There are no errors reported by Looking glass.
I've tried both the version provided by [https://extensions.gnome.org/extension/841/freon/](url) and the one provided by the AUR gnome-shell-extension-freon and they both have the same problem.

**Comment by UshakovVasilii** [comment]
Same issue #146
