### ISSUE TITLE
Error displaying Bumblebee Nvidia temperature 

### ISSUE THREAD

**Issue by re200484** [UshakovVasilii/gnome-shell-extension-freon#15]
Freon doesn't display the nvidia temperature, it shows me N/A; if i put this in the terminal:
optirun nvidia-smi -q -d TEMPERATURE 
i can see the current temperature.

==============NVSMI LOG==============

Timestamp                           : Fri Oct  9 19:05:09 2015
Driver Version                      : 355.11

Attached GPUs                       : 1
GPU 0000:01:00.0
    Temperature
        GPU Current Temp            : 60 C
        GPU Shutdown Temp           : N/A
        GPU Slowdown Temp           : N/A

**Comment by UshakovVasilii** [comment]
"Bumblebee+NVIDIA" display temperature if video card active only.
`optirun nvidia-smi -q -d TEMPERATURE ` command will activate video card, so it is not good approach

**Comment by zhulik** [comment]
Maybe, it will be better if that behavior will be explicit? Tooltip or any other help message?
