### ISSUE TITLE
Extreme fan speeds

### ISSUE THREAD

**Issue by 49studebaker** [UshakovVasilii/gnome-shell-extension-freon#155]
See attached images.

![fan](https://user-images.githubusercontent.com/18037226/70780672-afa78c00-1d4a-11ea-97c2-a48b43347f36.png)

![fan1](https://user-images.githubusercontent.com/18037226/70782424-9273bd00-1d4c-11ea-807e-fa96f614d5b6.png)

**Comment by UshakovVasilii** [comment]
Looks like it related to lm_sensors/drivers. You can execute `sensors` to check it.

**Comment by UshakovVasilii** [comment]
Looks like it related to lm_sensors/drivers. You can execute `sensors` to check it.

**Comment by jonasmalacofilho** [comment]
@49studebaker are you using an out-of-tree driver?

**Comment by jonasmalacofilho** [comment]
@49studebaker 

Please respond to feedback/comments on your issues.  I was ready to ignore #156 and only give it a look because it reproduces on my system as well.

**Comment by 49studebaker** [comment]
https://bugs.launchpad.net/ubuntu/+source/lm-sensors/+bug/1856457
