### ISSUE TITLE
classify hwmon NVME temperature as drive temperature

### ISSUE THREAD

**Issue by daenney** [UshakovVasilii/gnome-shell-extension-freon#159]
Starting with [Linux 5.5 the hwmon infrastructure now reports `temp` for NVME drives](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/drivers/nvme/host/hwmon.c?h=v5.5). These currently show up using Freon but it would be nice to be able to categorise those as disk temperature items, like the ones from smartctl, hddtemp, udisks2 and nvmecli.

It seems two things would be needed:
* read `/sys/class/hwmon/hwmon*/name`, this will return `nvme` for NVME drives
* use the `drive-temperature` icon for these temperature sensors instead

**Comment by daenney** [comment]
In my particular case sensors output has the following format:

```
nvme-pci-0100
Adapter: PCI adapter
Composite:
  temp1_{input,max,min,crit,alarm}
Sensor 1:
  temp2_{input,max,min}
Sensor 2:
  temp3_{input,max,min}
```

**Comment by illwieckz** [comment]
It looks like #218 took care of that (for now the drive names are not displayed).

**Comment by jonasmalacofilho** [comment]
That's true, I forgot to reference this issue.

The ~~drive~~ sensor names can be customized through `sensors.conf`.

**Comment by daenney** [comment]
The icon would appear to be wrong. I'm getting it as a generic temperature sensor (which the thermometer icon) whereas my SATA drives show up with a drive icon. It's not terribly inconvenient but the classification does help when there's a bunch of sensors showing up.

**Comment by jonasmalacofilho** [comment]
@daenney can you show me a screen shot?  And are any warnings or errors logged by freon/gnome-shell?

**Comment by daenney** [comment]
This is what it looks like for me
![Screenshot from 2021-11-20 18-41-22](https://user-images.githubusercontent.com/569574/142736118-1bad6f36-66b8-435b-9a25-f9b0881b05e6.png)


```
$ sensors -j
   "nvme-pci-0100":{
      "Adapter": "PCI adapter",
      "NVMe: primary":{
         "temp1_input": 29.850,
         "temp1_max": 80.850,
         "temp1_min": -0.150,
         "temp1_crit": 81.850,
         "temp1_alarm": 0.000
      },
      "Sensor 1":{
         "temp2_input": 29.850,
         "temp2_max": 65261.850,
         "temp2_min": -273.150
      },
      "Sensor 2":{
         "temp3_input": 30.850,
         "temp3_max": 65261.850,
         "temp3_min": -273.150
      }
   }
```

Nothing stands out in logs.

**Comment by jonasmalacofilho** [comment]
@daenney I can't see what could something like that (and can't reproduce it either).  What is the exact commit you're using (and have you made you don't have a dirty working tree)?

**Comment by daenney** [comment]
Ah! I'm at #214 / commit: a11b1ea. It looks like #217 / #218 might be what I need to get this to go full circle.

That's my bad, let me rebuild and double check that.

**Comment by daenney** [comment]
Right yup, that did it. Thanks for fixing this and my apologies for not catching I was on an older commit!
