### ISSUE TITLE
[Feature Request] Add support for NVIDIA PRIME render offload

### ISSUE THREAD

**Issue by s-kk** [UshakovVasilii/gnome-shell-extension-freon#161]
Hello!
NVIDIA added support for PRIME render offload since version 435.17. In this mode, iGPU is selected by default. If users want to render a particular application with nvidia GPU, simply add some environment variables and run the executable.

Here's my setup:
OS: Arch Linux
NV Driver version: 440.59 with modesetting

I can directly grab thermal data with nvidia-smi command. That means, you can simply add a mode to use nvidia-smi and grab the thermal output.

Thanks in advance. BTW wonderful extension!

Reference: [Arch Wiki](https://wiki.archlinux.org/index.php/PRIME#PRIME_render_offload)

**Comment by AlexWayfer** [comment]
> @s-kk closed this 35 minutes ago

Is it resolved?

**Comment by s-kk** [comment]
> > @s-kk closed this 35 minutes ago
> 
> 
> 
> Is it resolved?

Yes. And it works as expected.

**Comment by AlexWayfer** [comment]
> Yes. And it works as expected.

OK, thank you!
