### ISSUE TITLE
Freon undefined devices

### ISSUE THREAD

**Issue by xiamaz** [UshakovVasilii/gnome-shell-extension-freon#17]
Freon has 4 undefined devices in menu. Each of which appends a -5 every 5 seconds to its label. This has started after I used primusrun with bumblebee. Afterwards restarts and removal of freon extension has not fixed the problem.

Edit:
This seems to only happen, when Optistatus Extension is enabled at the same time. I am not sure how this happens. All that optistatus does is get the state of /proc/acpi/bbswitch every 3 seconds.

**Comment by UshakovVasilii** [comment]
Possible problem related to optistaus extension. And workaround is disable optistatus extension. So I won't fix problem for now
