### ISSUE TITLE
Ability to see CPU frequency

### ISSUE THREAD

**Issue by Tarballwalf** [UshakovVasilii/gnome-shell-extension-freon#207]
It would be nice to have it in one extension.

**Comment by UshakovVasilii** [comment]
I don't thinks so. I think this extension should be used for temperature only. 
https://extensions.gnome.org/extension/120/system-monitor/ good extension for cpu/memory/swap etc usage.

**Comment by AlexWayfer** [comment]
I wanted to say about "temperature-only extension" and mention System Monitor too, but then I saw fans speed and voltage and decided to left it for maintainer.

**Comment by UshakovVasilii** [comment]
Extension use `sensors` command, it returns temperature, fan speed and voltage.
I thought about removing them, but decided to keep them as option.
