### ISSUE TITLE
Support for GNOME 41

### ISSUE THREAD

**Issue by fabrixx** [UshakovVasilii/gnome-shell-extension-freon#211]
Hi, I'm creating a screencast for GNOME 41 and I'd like to show FREON too as I always have.
I would like to know if to get compatibility with GNOME 41 I can modify some file or recompile the addon by uninstalling the current one.

Thanks for all your work.

edit: changing version 41 in metadata work well for now

**Comment by UshakovVasilii** [comment]
Thank you! I uploaded new version to https://extensions.gnome.org, it's under review.

**Comment by fabrixx** [comment]
Thanks!
