### ISSUE TITLE
System lagging CPU spikes

### ISSUE THREAD

**Issue by MrSurly** [UshakovVasilii/gnome-shell-extension-freon#216]
I was seeing CPU spikes every 5 seconds which would cause even the GUI to lag.  Turns out it was this extension.  

This seems to be new with the Ubuntu 21.10 update.

**Comment by UshakovVasilii** [comment]
Hello, please check https://github.com/UshakovVasilii/gnome-shell-extension-freon/wiki/FAQ#system-to-hang-every-n-second

**Comment by JohnTheCoolingFan** [comment]
what's the process of finding which sensor is "bad"?
