### ISSUE TITLE
AticonfigUtil is not a constructor

### ISSUE THREAD

**Issue by telometto** [UshakovVasilii/gnome-shell-extension-freon#232]
I'm getting the error mentioned in the title. I cannot run the extension; I've tried uninstalling it, reinstalling it, removing the folder etc. but to no avail.

**Comment by telometto** [comment]
Easy fix. Disable Catalyst if you do not use the proprietary drivers and log out or reboot.

**Comment by bulgakke** [comment]
> Need just a little more context here. What is catalyst. What command should we use to disable it? looks like freon wants to execute a utility called aticonfig, and that's not installed on my system. Shouldn't it check if binary exists, and display a warning if it does not? (As opposed to crashing and all info going away?)

Tick this flag in the extensions's settings.
![image](https://user-images.githubusercontent.com/56848262/174630931-86c169d2-cabd-41bb-a8f6-242bd5f4c4d4.png)
