### ISSUE TITLE
Ability to turn off devices that are no longer available.

### ISSUE THREAD

**Issue by telometto** [UshakovVasilii/gnome-shell-extension-freon#233]
Is it possible to remove devices that are no longer available? I had an external SSD connected to the computer which broke, so now I have no longer access to the device; how can I remove the disconnected device?

Thanks.

EDIT: forgot to link picture.
![freon](https://user-images.githubusercontent.com/65364211/166117921-33ae7e5f-87db-4bd4-af6e-cdcf67a5721e.png)

**Comment by UshakovVasilii** [comment]
You need to change/reset the following key:
```
gsettings reset org.gnome.shell.extensions.freon hot-sensors
```
Or use UI: `dconf-editor`

**Comment by telometto** [comment]
Perfect! Thanks.
