### ISSUE TITLE
Translations for Russian 

### ISSUE THREAD

**Issue by wsxy162** [UshakovVasilii/gnome-shell-extension-freon#25]
I see the filename is "ru_RU.pot", a po translations file should be generated from the pot file, isn't edit directly to the "freon.pot". Maybe the author should update his translations file and rename it to "ru_RU.po".

**Comment by alsoijw** [comment]
Thank you very much. Is .mo file mandatory? #26

**Comment by wsxy162** [comment]
Yes, as I understand, .mo is a binary file building from .po file for the program, and .po file is for traslators.

**Comment by UshakovVasilii** [comment]
I generated `mo` file:  `msgfmt po/ru.po -o locale/ru/LC_MESSAGES/freon.mo`
According to https://wiki.gnome.org/Projects/GnomeShell/Extensions/FAQ/CreatingExtensions
