### ISSUE TITLE
No language source files provided

### ISSUE THREAD

**Issue by ViBE-HU** [UshakovVasilii/gnome-shell-extension-freon#254]
No `.po` files. Why?

**Comment by IsaacDias2020** [comment]
Same question.

**Comment by UshakovVasilii** [comment]
I reverted `.po` files. Looks like I removed them, I don't know reason, I think it was mistake...
Thanks!

**Comment by ViBE-HU** [comment]
Thanks. I thought that hungarian is poorly translated and that's why the plugin is still english on my system. But as I see it is a different issue. May the last compilation is made before the translation has been created?

**Comment by UshakovVasilii** [comment]
I recompiled `.mo` file, there is no diff
```
msgfmt po/hu.po -o locale/hu/LC_MESSAGES/freon.mo
```

**Comment by ViBE-HU** [comment]
Hm, that's pretty strange then. I'm on Ubuntu 20.04, everything is up to date and the whole application is in english somehow. The extension version is 40.
