### ISSUE TITLE
Update for G45

### ISSUE THREAD

**Issue by gilvbp** [UshakovVasilii/gnome-shell-extension-freon#266]
Hi, could you update to G45 version?
This tutorial might help:
https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm
Best regards.

If you need help, I could help with some code. Here's the official link. 

PS: Here it's a link to an extension that´s already working on G45 https://github.com/ionutbortis/gnome-bedtime-mode/tree/gnome45

**Comment by dinhokusanagi** [comment]
https://github.com/ionutbortis/gnome-bedtime-mode/tree/gnome45

ERRO

**Comment by menocheck** [comment]
Hi, I've started a pull request with some initial work: #267

**Comment by SeokYoung-Ahn** [comment]
It doesn't work on GNOME 45, I know you're busy, but please check. Please fix it. Thank you.

**Comment by syahn76** [comment]
Thank you so much for the update to gnome 45.

**Comment by dinhokusanagi** [comment]
thanks for the update
