### ISSUE TITLE
AticonfigUtil is not a constructor

### ISSUE THREAD

**Issue by davidfdr** [UshakovVasilii/gnome-shell-extension-freon#268]
Installed a new videocart RADEON RX 7900 XTX and the extension stopped working.

The error shown is **AticonfigUtil is not a constructor**
lspci:

03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX] (rev c8) (prog-if 00 [VGA controller])
        Subsystem: Tul Corporation / PowerColor Device 2422
        Flags: bus master, fast devsel, latency 0, IRQ 206, IOMMU group 14
        Memory at f000000000 (64-bit, prefetchable) [size=32G]
        Memory at f800000000 (64-bit, prefetchable) [size=256M]
        I/O ports at f000 [size=256]
        Memory at ec200000 (32-bit, non-prefetchable) [size=1M]
        Expansion ROM at ec300000 [disabled] [size=128K]
        Capabilities: [48] Vendor Specific Information: Len=08 <?>
        Capabilities: [50] Power Management version 3
        Capabilities: [64] Express Legacy Endpoint, MSI 00
        Capabilities: [a0] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Capabilities: [100] Vendor Specific Information: ID=0001 Rev=1 Len=010 <?>
        Capabilities: [150] Advanced Error Reporting
        Capabilities: [200] Physical Resizable BAR
        Capabilities: [240] Power Budgeting <?>
        Capabilities: [270] Secondary PCI Express
        Capabilities: [2a0] Access Control Services
        Capabilities: [2d0] Process Address Space ID (PASID)
        Capabilities: [320] Latency Tolerance Reporting
        Capabilities: [410] Physical Layer 16.0 GT/s <?>
        Capabilities: [450] Lane Margining at the Receiver <?>
        Kernel driver in use: amdgpu
        Kernel modules: amdgpu

---

I am using the following drivers:
Install AMD drivers on Ubuntu 20.04 from PPA third-party repository

ppa:oibaf/graphics-drivers

**Comment by illwieckz** [comment]
You don't need the AtiConfig option, this is for the old fglrx driver, which is incompatible with stock Ubuntu 20.04, it's also incompatible with your GPU, and for sure it is not installed on your system and you shouldn't anyway.

You should have nothing to do to enable AMD specific sensors in Freon as soon as you have `lm-sensors` installed.
