### ISSUE TITLE
Nvidia temperature not displayed?!

### ISSUE THREAD

**Issue by xdajog** [UshakovVasilii/gnome-shell-extension-freon#27]
Hi first all WOW! Really a GREAT extension - thank you so much!!

My problem:
I have a Nvidia gfx: NVIDIA Corporation GM204M [GeForce GTX 965M] installed are the proprietary nvidia driver together with bumblebee.

Executing the following command works fine:

    optirun nvidia-smi -q -d TEMPERATURE

Which gives back:

    Timestamp                           : Fri Mar  4 12:06:31 2016
    Driver Version                      : 361.28
    
    Attached GPUs                       : 1
    GPU 0000:01:00.0
    Temperature
        GPU Current Temp            : 39 C
        GPU Shutdown Temp           : 96 C
        GPU Slowdown Temp           : 91 C
 
The problem is that freon displays "N/A".. 
It doesn't matter if I set NVIDIA in the dropdown or bumblebee+NVIDIA (which would be my setup).

**Comment by UshakovVasilii** [comment]
Hi, Thank you!
Extension show temperature if video card work only.
You can check through `glxgears` https://wiki.archlinux.org/index.php/bumblebee#Test
