### ISSUE TITLE
Gnome 47 support

### ISSUE THREAD

**Issue by adequacy1** [UshakovVasilii/gnome-shell-extension-freon#288]
Not working on Gnome 47, Arch Linux.

**Comment by jonasmalacofilho** [comment]
Hey, take a look at PR #286 .

**Comment by adequacy1** [comment]
Thank you.

**Comment by ariejan** [comment]
@UshakovVasilii I'm seeing a lot of requests for Gnome 47 support for your Freon extension (myself included). 

I'm happy to help out with maintaining this extension. Feel free to reach out.

**Comment by UshakovVasilii** [comment]
Under review on https://extensions.gnome.org/

**Comment by cardil** [comment]
The EGO-57 tag is missing. Without it's difficult to update OS' packages like https://src.fedoraproject.org/rpms/gnome-shell-extension-freon/blob/rawhide/f/sources

@UshakovVasilii please, add the missing tag.

**Comment by UshakovVasilii** [comment]
Done
https://github.com/UshakovVasilii/gnome-shell-extension-freon/releases/tag/EGO-57
