### ISSUE TITLE
Leaking Memory

### ISSUE THREAD

**Issue by Ravice** [UshakovVasilii/gnome-shell-extension-freon#29]
gnome-shell is slowly leaking memory with freon enabled.

disabled all other extensions and restarted gnome-shell and usage is around 70-80mb stable, but with freon enabled, this is easily noticable as it increases at about 0.1MB every 5s or so, this never decreases, and i have caught gnome-shell using upwards of 400MB after about half a day uptime.

this is under GNOME 3.18 Ubuntu 15.10

**Comment by UshakovVasilii** [comment]
Actually it is not reproduced on by PC

**Comment by UshakovVasilii** [comment]
Problem is not reproduced, possible problem related to gnome-shell
