### ISSUE TITLE
assertion `CLUTTER_IS_TEXT (self)' failed

### ISSUE THREAD

**Issue by satriani-vai** [UshakovVasilii/gnome-shell-extension-freon#33]
The same [issue like by gnome-shell-extension-sensors](assertion `CLUTTER_IS_TEXT %28self%29' failed)

```
Jul 01 13:31:15 USER-PC org.gnome.Shell.desktop[977]: (gnome-shell:977): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Jul 01 13:31:15 USER-PC org.gnome.Shell.desktop[977]: (gnome-shell:977): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Jul 01 13:31:15 USER-PC org.gnome.Shell.desktop[977]: (gnome-shell:977): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed

$ uname -a
Linux USER-PC 4.6.3-1-ARCH #1 SMP PREEMPT Fri Jun 24 21:19:13 CEST 2016 x86_64 GNU/Linux

$ gnome-shell --version
GNOME Shell 3.20.3
```

gnome-shell-extension-freon was installed from [AUR](https://aur.archlinux.org/packages/gnome-shell-extension-freon-git/) which use a latest source fron git.

**Comment by terencode** [comment]
Yes, I have disable right now as it was causing gdm to crash randomly after exiting sleep.

**Comment by UshakovVasilii** [comment]
I'm sorry, but I cannot reproduce it and I have no idea what can cause it

**Comment by UshakovVasilii** [comment]
I cannot reproduce this problem on gnome 3.24.2, possible problem related to old gnome-shell version

**Comment by BillyCroan** [comment]
I'm getting it on gnome-shell-42.1-2.fc36.x86_64.
