### ISSUE TITLE
Minimize documentation duplication.

### ISSUE THREAD

**Issue by terrycloth** [UshakovVasilii/gnome-shell-extension-freon#40]
I was going to make a pull request with some minor updates to the project README, but I just noticed that some of the information gets duplicated in the wiki. So first I'll ask: Would you like to fold the wiki back into the project README? Or would you prefer to keep the README short, and document everything in the wiki? I can submit doc updates once you let me know :)

**Comment by UshakovVasilii** [comment]
Hi, I'm sorry for late reply.
I prefer keep the README short, and document everything in the wiki.
Thank you!
