### ISSUE TITLE
Finish or remove the placeholder copyright notices

### ISSUE THREAD

**Issue by terrycloth** [UshakovVasilii/gnome-shell-extension-freon#43]
All the files in `freon@UshakovVasilii_Github.yahoo.com/po/` contain a copyright comment at the top where all or some the important names are placeholders. This could confuse users and contributors as to the copyright/licensing status of the extension. It's also just weird to include these half-baked attribution notices :)

I'd submit a pull request for this, but I don't know which names go where.

**Comment by UshakovVasilii** [comment]
I just remove them, thanks
