### ISSUE TITLE
Bumblebee+NVIDIA temperature shows N/A

### ISSUE THREAD

**Issue by dosfanat** [UshakovVasilii/gnome-shell-extension-freon#47]
Hi! I think i found an incompatibility issue. Or a bug (much less probable)

Bumblebee+NVIDIA temperature shows N/A even when i am running something opengl-ish through primusrun or optirun. The result is simply the same - no value, omly N/A.

Laptop model: Acer 5750G
My distro: Debian 8.7 jessie
NVIDIA proprietary driver 340.101
Gnome Shell 3,14.4-1-deb8u
If needed - additional info will be quickly provided.

**Comment by dimmuboy** [comment]
old thing
[https://github.com/UshakovVasilii/gnome-shell-extension-freon/issues/15](url)

**Comment by UshakovVasilii** [comment]
Hi, I'm sorry for late reply.
Is `optirun nvidia-smi -q -d TEMPERATURE` return any info?

**Comment by dimmuboy** [comment]
In my case this command return

> NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

**Comment by UshakovVasilii** [comment]
It is reason of problem.
Problem out of gnome extension, so I close the ticket
