### ISSUE TITLE
AMDGPU support

### ISSUE THREAD

**Issue by Veske** [UshakovVasilii/gnome-shell-extension-freon#49]
Looks like maintainer is not active? Made my own fork with AMDGPU support. https://github.com/Veske/gnome-shell-extension-freon

If maintainer comes back, please pull changes in.

**Comment by UshakovVasilii** [comment]
Hi, I'm sorry for so late reply.
Is file `amdGpuSensors.conf` necessary for AMD gpu support? We cannot pack this file into zip archive for https://extensions.gnome.org

**Comment by UshakovVasilii** [comment]
Ah, we can monitor AMD from sensors utility, so we not need any special configuration and code modification. Am I wrong?

**Comment by Veske** [comment]
Yes, sensors conf would be there just for convenience. You can change the format of sensor output with it.

**Comment by UshakovVasilii** [comment]
So #38 enough for AMDGPU support.
Thanks!
