### ISSUE TITLE
Support for nvidia optimus?

### ISSUE THREAD

**Issue by spacepluk** [UshakovVasilii/gnome-shell-extension-freon#5]
It would be cool to show the temperature of the gpu when it's enabled.

**Comment by UshakovVasilii** [comment]
Oh, I hate "optimus"...
As I understand nouveau and [nvidia without dynamic switching GPU](https://wiki.archlinux.org/index.php/NVIDIA_Optimus#Using_nvidia)  should work.
Do you use [Bumblebee](https://wiki.archlinux.org/index.php/Bumblebee)?

**Comment by spacepluk** [comment]
Hehehe, yeah I used to hate it too.
I'm using bumblebee with nvidia drivers, but gnome is running on the intel. I only run certain applications with optirun when I want the nvidia to kick in.  Should it work in this situation?

For example, if I run:

    optirun glxgears

and then check the temperatures I can't see the values for the gpu.

Maybe I'm missing something.

**Comment by UshakovVasilii** [comment]
Got it,
I will check with bumblebee on this week.
Thanks

**Comment by spacepluk** [comment]
Thank you :)
Let me know if I you need more info/testing.

**Comment by UshakovVasilii** [comment]
Done! "bumblebee-nvidia" branch. 
I added "Bumblebee + nvidia" utility (option in config).
I'm using `optirun nvidia-smi -L` for detect GPU name and `optirun nvidia-smi -q -d TEMPERATURE` for detect temperature. Commands are executed if GPU is working only.
I'll test more, merge into master and upload to extensions.gnome.org on next week.

**Comment by googol42** [comment]
:+1:

**Comment by spacepluk** [comment]
woot! thanks :)

**Comment by UshakovVasilii** [comment]
uploaded to extensions.gnome.org
