### ISSUE TITLE
Inadvertent settings causes system to hang.

### ISSUE THREAD

**Issue by bluevoxInc** [UshakovVasilii/gnome-shell-extension-freon#51]
I was playing around with the settings and inadvertently set NVDIA graphics card, which is not installed on my system. This caused my desktop to hang and I could not recover even after rebooting. I had to open a command line after reboot and uninstall the extension before I could get back to my desktop. I could not even disable the extension using:

$ gnome-shell-extension-tool -d Freon (I tried 'freon', the uid etc)

I even tried to edit the metadata file to reset the card back to the original, all to no avail.

This extension should be made slightly more idiot proof.

**Comment by UshakovVasilii** [comment]
Hi, I think NVIDIA setting is not reason of problem.
Application search `nvidia-settings` command and do nothing if command is not available.
Possible you have problem with `sensors` command.
You can try to execute `sensors` command to check system hang.
Thanks
