### ISSUE TITLE
Provide translation template (pot file)

### ISSUE THREAD

**Issue by jonnius** [UshakovVasilii/gnome-shell-extension-freon#52]
I would like to provide a German translation, but i couldn't find the translation template file (*.pot). Please add it to the po folder!

**Comment by UshakovVasilii** [comment]
Hi, I'm sorry for late reply.
file was in `po` folder. `freon.pot`
https://github.com/UshakovVasilii/gnome-shell-extension-freon/blob/master/freon%40UshakovVasilii_Github.yahoo.com/po/freon.pot
