### ISSUE TITLE
No temperatures shown in bar with no discrete GPU

### ISSUE THREAD

**Issue by DuBistKomisch** [UshakovVasilii/gnome-shell-extension-freon#59]
From the screenshots I've seen it's meant to show some sort of average temperature next to the icon in the bar, but all I see is the first icon:

![screenshot from 2017-08-18 22-41-47](https://user-images.githubusercontent.com/703055/29459335-80c541fe-8466-11e7-8e68-d8f1dd326f40.png)

I use VFIO / GPU passthrough to a windows VM, and run Arch as a host on the integrated GPU, so I don't expect to be able to see the discrete GPU temperature. I've selected "None" for "Video Card Temperature Utility" so not sure what it's trying to do.

**Comment by UshakovVasilii** [comment]
You can click to icon and select indicator to show

**Comment by DuBistKomisch** [comment]
Haha, so you can, oops. Feel free to close this.

Maybe should be mentioned explicitly somewhere? Or default to average?

**Comment by UshakovVasilii** [comment]
I create issue #60
Thanks!
