### ISSUE TITLE
Wrong average temperature, when dedicated is deactivated

### ISSUE THREAD

**Issue by googol42** [UshakovVasilii/gnome-shell-extension-freon#6]
Hello,

I am running gnome 3.16. I have an i7 with dedicated graphics card, which I only enable for special software (by using optirun). While the dedicated graphics card is not enabled, the average temperature is not calculated correctly. See the attached image: 
![wrong-temperature](https://cloud.githubusercontent.com/assets/9155562/7200633/36812c06-e4ff-11e4-87bb-5892efcbbc16.png)

**Comment by UshakovVasilii** [comment]
Thank you!

**Comment by googol42** [comment]
> Thank you!

Thanks for fixing the bug that fast. I tested the change, and can confirm that it fixes the issue.
