### ISSUE TITLE
Support for AMDGPU Temperature

### ISSUE THREAD

**Issue by Styx85** [UshakovVasilii/gnome-shell-extension-freon#70]
Is it possible to integrate AMDGPU temperature support like [Veske did in the Freon Fork](https://github.com/Veske/gnome-shell-extension-freon/commit/28587e52d08b7cdb82b32f034e26af10bccd5356)? 

It would be nice to have.

**Comment by UshakovVasilii** [comment]
It was done https://github.com/UshakovVasilii/gnome-shell-extension-freon/issues/49#issuecomment-307306882

**Comment by Styx85** [comment]
Oh yes sorry, I missed that.
