### ISSUE TITLE
gnome-shell crash in st_label_set_text

### ISSUE THREAD

**Issue by hedgepigdaniel** [UshakovVasilii/gnome-shell-extension-freon#74]
Unfortunately the fix for #71 didn't fix all the crashes, although it does make them much less frequent. I got another one today with freon 32:

#0   0x1ffefff760 b   /usr/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/extension.js:360 (0x43596d58 @ 1995)
#1   0x1ffefff7c0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x3b8c2bc0 @ 71)
#2   0x1ffefff860 b   /usr/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/extension.js:231 (0x43596c48 @ 17)
#3   0x1ffefff8e0 I   self-hosted:913 (0x3b8ee5e8 @ 346)
#4   0x1ffefff990 b   /usr/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/commandLineUtil.js:38 (0x435a0808 @ 454)
#5   0x1ffefffa60 I   self-hosted:917 (0x3b8ee5e8 @ 394)

**Comment by UshakovVasilii** [comment]
@hedgepigdaniel Hello, can you check version from master?
I removed UI update from background threads, it can cause UI delay, but looks like we have not other option :-(
