### ISSUE TITLE
Broken text of icon at panel in Russian locale

### ISSUE THREAD

**Issue by AlexWayfer** [UshakovVasilii/gnome-shell-extension-freon#76]
![image](https://user-images.githubusercontent.com/6510020/33550379-b7ed380c-d8fe-11e7-8812-94be4779fb1e.png)

**Comment by UshakovVasilii** [comment]
It usually happen if selected sensor unavailable. Try to reselect sensor (Click on sensor which should be shown on top panel).

**Comment by AlexWayfer** [comment]
@UshakovVasilii I've just changed DE language from English, where it's displaying correctly, to Russian. And this behavior confused me. After switching back to English everything is normal. What about saving selected value between locales?

**Comment by UshakovVasilii** [comment]
I created #77 ticket for this. Thanks
