### ISSUE TITLE
GPU Temp erroneously shown when GPU is offline

### ISSUE THREAD

**Issue by rahulkolasseri** [UshakovVasilii/gnome-shell-extension-freon#78]
When the GPU is offline, the sensor goes offline as well and Freon shows a useless reading instead of a Blank/OFF value. If showing average sensor temperature, it takes this erroneous value into account as well instead of discarding it, making the average value shown completely wrong too.

Eg.
![image](https://user-images.githubusercontent.com/223131/34483918-6a24f4d8-effc-11e7-972f-07ce4063132f.png)
(Fan, CPU, GPU offline, HDD)

![image](https://user-images.githubusercontent.com/223131/34484015-034c7398-effd-11e7-933e-94eb3e5710db.png)
(Fan, CPU, GPU online, HDD)

**Comment by UshakovVasilii** [comment]
> When the GPU is offline, the sensor goes offline as well and Freon shows a useless reading instead of a Blank/OFF value. 

As I understand you use Bumblebee+NVIDIA for GPU monitoring.
When GPU online file `/tmp/.X:8` should exist but looks like you don't have this file and GPU monitoring command `optirun nvidia-smi -q -d TEMPERATURE` executed and got wrong value. Please check `/tmp/.X:8` file and `/etc/bumblebee/bumblebee.conf`#VirtualDisplay= value.

> If showing average sensor temperature, it takes this erroneous value into account as well instead of discarding it, making the average value shown completely wrong too.

It is problem, currently temperatures from `lm_sensors` only involve in average temperature calculation. I will fix it later #81

**Comment by rahulkolasseri** [comment]
Actually I am using AMD, not Nvidia. And I have selected "Catalyst" under "Video card temp. utility", and it works when the card is online although I don't have catalyst installed, am using the AMDGPU drivers instead.

**Comment by UshakovVasilii** [comment]
ok, please provide `aticonfig --odgt` output with on/off Catalyst

**Comment by UshakovVasilii** [comment]
deprecated
