### ISSUE TITLE
Hddtemp did`t work with extensions-freon

### ISSUE THREAD

**Issue by AyzekUorren** [UshakovVasilii/gnome-shell-extension-freon#95]
[Example 1](https://image.ibb.co/iQHG59/Screenshot_from_2018_08_27_16_00_58.png)

Work alone: [Example](https://image.ibb.co/fic5yU/Screenshot_from_2018_08_27_16_02_05.png)

**Comment by UshakovVasilii** [comment]
Closed?

**Comment by AyzekUorren** [comment]
It's last version bug hddtemp

**Comment by UshakovVasilii** [comment]
Got it, thanks
